# Generated by Django 4.2.2 on 2023-06-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id_caracteristica', models.IntegerField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField()),
                ('nombre', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'caracteristica',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id_evaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=300)),
                ('nota_final', models.IntegerField()),
            ],
            options={
                'db_table': 'evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Subategoria',
            fields=[
                ('id_subcategoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('calificacion', models.IntegerField()),
                ('caracteristicas', models.ManyToManyField(to='evaluacion.caracteristica')),
            ],
            options={
                'db_table': 'subategoria',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=300)),
                ('calificacion', models.IntegerField()),
                ('caracteristicas', models.ManyToManyField(to='evaluacion.caracteristica')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id_alimentos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('estilo', models.CharField(max_length=80)),
                ('categorias', models.ManyToManyField(to='evaluacion.categoria')),
            ],
            options={
                'db_table': 'alimentos',
            },
        ),
    ]
