# Generated by Django 4.2.2 on 2023-06-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='id_alimentos',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='id_caracteristica',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='id_evaluacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subategoria',
            name='id_subcategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
