# Generated by Django 4.2.2 on 2023-06-21 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_alter_alimentos_id_alimentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caracteristica',
            name='valoracion',
        ),
        migrations.RemoveField(
            model_name='subategoria',
            name='calificacion',
        ),
    ]
