# Generated by Django 4.2.2 on 2023-06-21 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_remove_caracteristica_valoracion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='calificacion',
        ),
    ]
