# Generated by Django 4.2.2 on 2023-08-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_remove_categoria_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='estilo',
            field=models.CharField(default='cartagena', max_length=50),
            preserve_default=False,
        ),
    ]
