# Generated by Django 4.2.2 on 2023-08-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_estilo_remove_alimentos_estilo_alimentos_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
