# Generated by Django 4.2.2 on 2023-08-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0008_alter_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='subcategorias',
            field=models.ManyToManyField(blank=True, to='evaluacion.subategoria'),
        ),
    ]
