# Generated by Django 4.2.2 on 2023-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0009_categoria_subcategorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='notas',
            field=models.JSONField(default=dict),
        ),
    ]
